name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (optional)
        run: |
          python -m pyflakes || true
        continue-on-error: true

      - name: Build sanity
        run: |
          python -V
          python - << 'PY'
          import yaml, sys
          print('config.yml ok:', bool(open('config.yml').read()))
          PY

      - name: Deploy to Heroku
        if: ${{ success() }}
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

      - name: Release on GitHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
